/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.panel.radnik;

import view.panel.opstaekranskaforma.OpstaEkranskaForma;
import domen.OpstiDomenskiObjekat;
import domen.Radnik;
import domen.Zadatak;
import domen.Zaduzenje;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import model.ZadaciTableModel;
import sesija.Sesija;
import view.kontorler.radnik.PredavanjeZadatkaKontroler;

/**
 *
 * @author aleksandar
 */
public class PredavanjeZadatkaPanel extends javax.swing.JPanel implements OpstaEkranskaForma {
    
    ZadaciTableModel model;
    Zadatak trenutniZadatak;
    PredavanjeZadatkaKontroler kontroler;

    /**
     * Creates new form PredavanjeZadatkaPanel
     */
    public PredavanjeZadatkaPanel() {
        initComponents();
        model = new ZadaciTableModel();
        jTable1.setModel(model);
        kontroler = new PredavanjeZadatkaKontroler(this);
        popuniCombo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButtonPredaj = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Naziv", "Rok", "Status", "Opis"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 660, 160));

        jLabel1.setText("Moji zadaci:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jButtonPredaj.setText("Predaj");
        jButtonPredaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPredajActionPerformed(evt);
            }
        });
        add(jButtonPredaj, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 240, 110, 40));

        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 330, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        trenutniZadatak = (Zadatak) jComboBox1.getSelectedItem();
        dodajZadatak(trenutniZadatak);
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButtonPredajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPredajActionPerformed
        if (trenutniZadatak != null) {
            try {
                kontroler.predajZadatak();
                popuniCombo();
                model.setZadaci(new ArrayList<Zadatak>());
            } catch (IOException | ClassNotFoundException ex) {
                ex.printStackTrace();
            }
        } else {
            JOptionPane.showMessageDialog(this, "Prvo odaberite zadatak!");
        }

    }//GEN-LAST:event_jButtonPredajActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonPredaj;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    private void popuniCombo() {
        List<Zadatak> zadaci = new ArrayList<>();
        Radnik r = (Radnik) Sesija.getInstance().getKorisnik();
        for (Zaduzenje z : r.getZaduzenje()) {
            if (!z.getZadatak().getStatus().startsWith("z")) {
                zadaci.add(z.getZadatak());
            }
        }
        jComboBox1.setModel(new DefaultComboBoxModel(zadaci.toArray()));
    }
    
    public void dodajZadatak(Zadatak z) {
        if (z != null) {
            model.prikaziZadatak(z);
        }
    }
    
    public OpstiDomenskiObjekat vratiTrenutniZadatak() {
        return trenutniZadatak;
    }
    
    public void izmeni() {
        popuniCombo();
        model.setZadaci(new ArrayList<Zadatak>());
    }
}
