/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.panel.zadatak;

import domen.Radnik;
import domen.Zadatak;
import domen.Zaduzenje;
import java.io.IOException;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import view.kontorler.menadzer.ZaduzenjeKontroler;
import view.panel.opstaekranskaforma.OpstaEkranskaForma;

/**
 *
 * @author aleksandar
 */
public class DodeljivanjeZadatkaPanel extends javax.swing.JPanel implements OpstaEkranskaForma {

    ZaduzenjeKontroler kontroler;

    /**
     * Creates new form DodeljivanjeZadatkaPanel
     */
    public DodeljivanjeZadatkaPanel() {
        initComponents();
        kontroler = new ZaduzenjeKontroler(this);
        popuniCombo();
        postaviDatum();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelPodaci = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldDatum = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jComboBoxRadnici = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBoxZadaci = new javax.swing.JComboBox();
        jButtonKreirajNovo = new javax.swing.JButton();

        jPanelPodaci.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanelPodaci.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setText("Datum dodele:");
        jPanelPodaci.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 29, -1, -1));

        jLabel4.setText("Napomena:");
        jPanelPodaci.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 58, 110, 30));

        jTextFieldDatum.setEditable(false);
        jPanelPodaci.add(jTextFieldDatum, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 24, 221, -1));

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        jPanelPodaci.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 58, 377, -1));

        jComboBoxRadnici.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "" }));

        jLabel1.setText("Radnici:");

        jLabel2.setText("Zadaci:");

        jComboBoxZadaci.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "" }));

        jButtonKreirajNovo.setText("Zaduzi");
        jButtonKreirajNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonKreirajNovoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelPodaci, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(11, 11, 11)
                                .addComponent(jComboBoxZadaci, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(8, 8, 8)
                                .addComponent(jComboBoxRadnici, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonKreirajNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)))))
                .addGap(4, 12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel1))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jComboBoxRadnici, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonKreirajNovo)))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel2))
                    .addComponent(jComboBoxZadaci, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addComponent(jPanelPodaci, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonKreirajNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonKreirajNovoActionPerformed
        try {
            kontroler.sacuvajZaduzenje();
        } catch (IOException | ClassNotFoundException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jButtonKreirajNovoActionPerformed

    public Object getSelectedRadnik() {
        return jComboBoxRadnici.getSelectedItem();
    }

    public Object getSelectedZadatak() {
        return jComboBoxZadaci.getSelectedItem();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonKreirajNovo;
    private javax.swing.JComboBox jComboBoxRadnici;
    private javax.swing.JComboBox jComboBoxZadaci;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanelPodaci;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextFieldDatum;
    // End of variables declaration//GEN-END:variables

    private void popuniCombo() {
        List<Radnik> radnici;
        List<Zadatak> zadaci;
        try {
            radnici = kontroler.vratiRadnike();
            zadaci = kontroler.vratiZadatke();
            jComboBoxRadnici.setModel(new DefaultComboBoxModel(radnici.toArray()));
            jComboBoxZadaci.setModel(new DefaultComboBoxModel(zadaci.toArray()));
        } catch (IOException | ClassNotFoundException ex) {
            ex.printStackTrace();
        }

    }

    private void postaviDatum() {
        Date danas = new Date();
        SimpleDateFormat sf = new SimpleDateFormat("yyyy-MM-dd");
        jTextFieldDatum.setText(sf.format(danas));
    }

    public String getNapomena() {
        return jTextArea2.getText();
    }

    public Date getDatum() {
        Date d = null;
        DateFormat df = new SimpleDateFormat("yyyy-MM-dd");

        String sDate = jTextFieldDatum.getText();
        try {
            d = df.parse(sDate);
        } catch (ParseException ex) {
            ex.printStackTrace();
        }
        return d;
    }
}
