/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.panel.zadatak;

import domen.Zadatak;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import model.ZadaciTableModel;
import view.kontorler.menadzer.IzmenaBrisanjeKontroler;
import view.panel.opstaekranskaforma.OpstaEkranskaForma;

/**
 *
 * @author Sanja
 */
public class IzmenaBrisanjeZadatakaPanel extends javax.swing.JPanel implements OpstaEkranskaForma {

    ZadaciTableModel model;
    IzmenaBrisanjeKontroler kontroler;

    /**
     * Creates new form IzmenaBrisanjeBiciklistaPanel
     */
    public IzmenaBrisanjeZadatakaPanel() {
        initComponents();
        model = new ZadaciTableModel();
        jTable1.setModel(model);
        kontroler = new IzmenaBrisanjeKontroler(this);
        jButtonIzmeni.setEnabled(false);
        jButtonObrisi.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pretraziButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        statusTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        IDTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nazivTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        rokTextField = new javax.swing.JTextField();
        jButtonObrisi = new javax.swing.JButton();
        jButtonIzmeni = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pretraziButton.setText("Pretrazi zadatke");
        pretraziButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pretraziButtonActionPerformed(evt);
            }
        });
        add(pretraziButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 153, 145, -1));

        jLabel6.setText("Status:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 160, -1, -1));

        statusTextField.setName(""); // NOI18N
        add(statusTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 155, 130, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Naziv", "Rok", "Status", "Opis"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 252, 480, 107));

        jLabel5.setText("Rok");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 126, -1, -1));

        IDTextField.setName(""); // NOI18N
        IDTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDTextFieldActionPerformed(evt);
            }
        });
        add(IDTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 53, 130, -1));

        jLabel1.setText("Rezultat pretrage:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 228, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Pretraga zadataka");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 12, -1, -1));

        jLabel3.setText("ID:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 58, -1, -1));

        nazivTextField.setName(""); // NOI18N
        add(nazivTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 87, 130, -1));

        jLabel4.setText("Naziv:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 92, -1, -1));

        rokTextField.setName(""); // NOI18N
        add(rokTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 121, 130, -1));

        jButtonObrisi.setText("Obrisi  zadatak");
        jButtonObrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonObrisiActionPerformed(evt);
            }
        });
        add(jButtonObrisi, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 320, 163, -1));

        jButtonIzmeni.setText("Izmeni  zadatak");
        jButtonIzmeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIzmeniActionPerformed(evt);
            }
        });
        add(jButtonIzmeni, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 280, 163, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void IDTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IDTextFieldActionPerformed

    private void pretraziButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pretraziButtonActionPerformed
        try {
            kontroler.pretraziZadatke();
            jButtonIzmeni.setEnabled(true);
            jButtonObrisi.setEnabled(true);
        } catch (IOException | ClassNotFoundException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_pretraziButtonActionPerformed

    private void jButtonIzmeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIzmeniActionPerformed
        int index = jTable1.getSelectedRow();
        if (index < 0) {
            JOptionPane.showMessageDialog(this, "Prvo izaberite zadatak!");
            return;
        }
        int option = JOptionPane.showConfirmDialog(this, "Sigurno zelite da izmenite selektovani zadatak?");
        if (option == JOptionPane.YES_OPTION) {

            Zadatak z = model.vratiZadatak(index);
            try {
                kontroler.izmeniZadatak(z);
            } catch (IOException | ClassNotFoundException ex) {
                ex.printStackTrace();
            }
        }

    }//GEN-LAST:event_jButtonIzmeniActionPerformed

    private void jButtonObrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonObrisiActionPerformed
        int index = jTable1.getSelectedRow();
        if (index < 0) {
            JOptionPane.showMessageDialog(this, "Prvo izaberite zadatak!");
            return;
        }

        int option = JOptionPane.showConfirmDialog(this, "Sigurno zelite da obrisete selektovani zadatak?");
        if (option == JOptionPane.YES_OPTION) {
            Zadatak z = model.vratiZadatak(index);
            try {
                kontroler.obrisiZadatak(z);
            } catch (IOException | ClassNotFoundException ex) {
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_jButtonObrisiActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField IDTextField;
    private javax.swing.JButton jButtonIzmeni;
    private javax.swing.JButton jButtonObrisi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField nazivTextField;
    private javax.swing.JButton pretraziButton;
    private javax.swing.JTextField rokTextField;
    private javax.swing.JTextField statusTextField;
    // End of variables declaration//GEN-END:variables

    public void dodajUTabelu(List<Zadatak> list) {
        if (list != null) {
            model.setZadaci(list);
        } else {
            model.setZadaci(new ArrayList<Zadatak>());
        }
    }

    public String getID() {
        return IDTextField.getText();
    }

    public void setID(String id) {
        this.IDTextField.setText(id);
    }

    public String getNaziv() {
        return nazivTextField.getText();
    }

    public void setNaziv(String naziv) {
        this.nazivTextField.setText(naziv);
    }

    public String getRok() {
        return rokTextField.getText();
    }

    public void setRok(String rok) {
        this.rokTextField.setText(rok);
    }

    public String getStatus() {
        return statusTextField.getText();
    }

    public void setStatus(String status) {
        this.statusTextField.setText(status);
    }

}
