/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.panel.zadatak;

import domen.Zadatak;
import java.io.IOException;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import model.ZadaciTableModel;
import view.kontorler.menadzer.PretragaZadatkaKontroler;
import view.panel.opstaekranskaforma.OpstaEkranskaForma;

/**
 *
 * @author Aleksandar
 */
public class PretragaZadatakaPanel extends javax.swing.JPanel implements OpstaEkranskaForma {

    ZadaciTableModel model;

    PretragaZadatkaKontroler kontroler;

    /**
     * Creates new form PretragaBiciklistaPanel
     */
    public PretragaZadatakaPanel() {
        initComponents();
        model = new ZadaciTableModel();
        jTable1.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        IDTextField = new javax.swing.JTextField();
        pretraziButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nazivTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        rokTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        statusTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        IDTextField.setName(""); // NOI18N
        add(IDTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(134, 48, 130, -1));

        pretraziButton.setText("Pretrazi zadatke");
        pretraziButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pretraziButtonActionPerformed(evt);
            }
        });
        add(pretraziButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 150, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Naziv", "Rok", "Status", "Opis"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 233, 610, 160));

        jLabel1.setText("Rezultat pretrage:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 203, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Pretraga zadataka");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 12, -1, -1));

        jLabel3.setText("ID:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 58, -1, -1));

        nazivTextField.setName(""); // NOI18N
        add(nazivTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(134, 82, 130, -1));

        jLabel4.setText("Naziv:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 87, -1, -1));

        rokTextField.setName(""); // NOI18N
        add(rokTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(134, 116, 130, -1));

        jLabel5.setText("Rok za izvrsenje:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 121, -1, -1));

        statusTextField.setName(""); // NOI18N
        add(statusTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(134, 151, 130, -1));

        jLabel6.setText("Status:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 156, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void pretraziButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pretraziButtonActionPerformed
        kontroler = new PretragaZadatkaKontroler(this);
        try {
            kontroler.pretraziZadatke();
        } catch (IOException | ClassNotFoundException ex) {
            Logger.getLogger(PretragaZadatakaPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_pretraziButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField IDTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField nazivTextField;
    private javax.swing.JButton pretraziButton;
    private javax.swing.JTextField rokTextField;
    private javax.swing.JTextField statusTextField;
    // End of variables declaration//GEN-END:variables

    public void dodajUTabelu(List<Zadatak> list) {
        if (list != null) {
            model.setZadaci(list);
        } else {
            model.setZadaci(new ArrayList<Zadatak>());
        }
    }

    public String getID() {
        String s = IDTextField.getText();
        if (s == null || s.isEmpty()) {
            return "-1";
        }
        return s;
    }

    public String getNaziv() {
        return nazivTextField.getText();
    }

    public Date getRok() {
        Date d = null;
        DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
        if (rokTextField.getText().isEmpty()) {
            try {
                d = df.parse("2020-12-23");
            } catch (ParseException ex) {
                ex.printStackTrace();
            }
        } else {
            String sDate = rokTextField.getText();
            try {
                d = df.parse(sDate);
            } catch (ParseException ex) {
                ex.printStackTrace();
            }
        }
        return d;
    }

    public String getStatus() {
        return statusTextField.getText();
    }
}
