/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.panel.zadatak;

import domen.Slika;
import domen.Zadatak;
import java.awt.Color;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import model.SlikeTableModel;
import validacija.Validacija;
import view.kontorler.menadzer.UnosZadatkaKontroler;
import view.panel.opstaekranskaforma.OpstaEkranskaForma;

/**
 *
 * @author Sanja
 */
public class UnosZadatkaPanel extends javax.swing.JPanel implements OpstaEkranskaForma {

    UnosZadatkaKontroler kontroler;
    BufferedImage ucitanaSlika;
    String putanja;
    SlikeTableModel model;
    Zadatak trenutniZadatak;

    public SlikeTableModel getModel() {
        return model;
    }

    /**
     * Creates new form UnosPutovanjaPanel
     */
    public UnosZadatkaPanel() {
        initComponents();
        kontroler = new UnosZadatkaKontroler(this);
        model = new SlikeTableModel();
        jTable1.setModel(model);
        ucitanaSlika = null;
        sacuvajZadatakBtn.setEnabled(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser = new javax.swing.JFileChooser();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        idTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        nazivZadatkaTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        rokTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        statusTextField = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        TextFieldSlika = new javax.swing.JTextField();
        izborFajlaButton = new javax.swing.JButton();
        dodajUTabelu = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        imagePreview = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButtonNovi = new javax.swing.JButton();
        sacuvajZadatakBtn = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaOpis = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();

        jPanel1.setLayout(new java.awt.GridLayout(4, 2, 0, 5));

        jLabel1.setText("Zadatak ID:");
        jPanel1.add(jLabel1);

        idTextField.setEnabled(false);
        jPanel1.add(idTextField);

        jLabel2.setText("Naziv zadatka:");
        jPanel1.add(jLabel2);
        jPanel1.add(nazivZadatkaTextField);

        jLabel3.setText("Rok za izvrsenje:");
        jPanel1.add(jLabel3);
        jPanel1.add(rokTextField);

        jLabel4.setText("Status:");
        jPanel1.add(jLabel4);
        jPanel1.add(statusTextField);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Slike"));

        TextFieldSlika.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldSlikaActionPerformed(evt);
            }
        });

        izborFajlaButton.setText("Izaberi fajl");
        izborFajlaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                izborFajlaButtonActionPerformed(evt);
            }
        });

        dodajUTabelu.setText("Dodaj");
        dodajUTabelu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dodajUTabeluActionPerformed(evt);
            }
        });

        jLabel6.setText("Slika:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(TextFieldSlika, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(izborFajlaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(imagePreview, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dodajUTabelu, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(TextFieldSlika, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(izborFajlaButton))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(dodajUTabelu, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(imagePreview, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 8, Short.MAX_VALUE))))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Opis"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButtonNovi.setText("Novi Zadatak");
        jButtonNovi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNoviActionPerformed(evt);
            }
        });

        sacuvajZadatakBtn.setText("Sacuvaj Zadatak");
        sacuvajZadatakBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sacuvajZadatakBtnActionPerformed(evt);
            }
        });

        jLabel7.setText("Opis:");

        jTextAreaOpis.setColumns(20);
        jTextAreaOpis.setRows(5);
        jScrollPane2.setViewportView(jTextAreaOpis);

        jLabel5.setText("Format: yyyy-MM-dd");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(jLabel5)
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonNovi, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sacuvajZadatakBtn)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(99, 99, 99)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonNovi)
                        .addGap(10, 10, 10)
                        .addComponent(sacuvajZadatakBtn)))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void izborFajlaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_izborFajlaButtonActionPerformed
        int opcija = jFileChooser.showOpenDialog(this);
        File fajl = null;
        if (opcija == JFileChooser.APPROVE_OPTION) {
            fajl = jFileChooser.getSelectedFile();
            // TextFieldSlika.setText(fajl.getName());
            this.putanja = fajl.getAbsolutePath();
            TextFieldSlika.setText(fajl.getName());
            try {
                ucitanaSlika = ImageIO.read(fajl);
                imagePreview.setIcon(new ImageIcon(ucitanaSlika.getScaledInstance(200, 110, Image.SCALE_SMOOTH)));
            } catch (IOException ex) {
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_izborFajlaButtonActionPerformed

    private void TextFieldSlikaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldSlikaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldSlikaActionPerformed

    private void jButtonNoviActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNoviActionPerformed
        kontroler = new UnosZadatkaKontroler(this);
        try {
            kontroler.kreirajNoviZadatak();
            sacuvajZadatakBtn.setEnabled(true);
        } catch (IOException | ClassNotFoundException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jButtonNoviActionPerformed

    private void sacuvajZadatakBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sacuvajZadatakBtnActionPerformed

        if (!Validacija.daLiSuSvaPopunjena(getNazivZadatka(), getStatus(), getOpis(), rokTextField.getText())) {
            JOptionPane.showMessageDialog(this, "Molimo popunite sva polja!");
            return;
        }

        if (!Validacija.datumFormatOk(rokTextField.getText())) {
            JOptionPane.showMessageDialog(this, "Format datuma nije dobar!!");
            rokTextField.setBackground(Color.RED);
            return;
        }

        if (!Validacija.datumVeciOdDanas(rokTextField.getText())) {
            JOptionPane.showMessageDialog(this, "Datum ne sme biti manji od danasnjeg!!");
            rokTextField.setBackground(Color.RED);
            return;
        }

        trenutniZadatak = (Zadatak) kontroler.vratiOpstiDomenskiObjekat();
        trenutniZadatak.setNoveSlike(model.getSlike());
        try {

            kontroler.sacuvajZadatak();
        } catch (IOException | ClassNotFoundException ex) {
            Logger.getLogger(UnosZadatkaPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        model.setSlike(new ArrayList<Slika>());
    }//GEN-LAST:event_sacuvajZadatakBtnActionPerformed

    private void dodajUTabeluActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dodajUTabeluActionPerformed
        Slika slika = new Slika();
        slika.setZadatak(new Zadatak(Integer.parseInt(this.getIdTextField()), null, null, null, null, null, null, null));
        slika.setNaziv(TextFieldSlika.getText().trim());
        slika.setId(jTable1.getRowCount() + 1);
        slika.setSlika(ucitanaSlika);
        slika.setPutanjaDoSlike(putanja);
        model.dodajSliku(slika);
    }//GEN-LAST:event_dodajUTabeluActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TextFieldSlika;
    private javax.swing.JButton dodajUTabelu;
    private javax.swing.JTextField idTextField;
    private javax.swing.JLabel imagePreview;
    private javax.swing.JButton izborFajlaButton;
    private javax.swing.JButton jButtonNovi;
    private javax.swing.JFileChooser jFileChooser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextAreaOpis;
    private javax.swing.JTextField nazivZadatkaTextField;
    private javax.swing.JTextField rokTextField;
    private javax.swing.JButton sacuvajZadatakBtn;
    private javax.swing.JTextField statusTextField;
    // End of variables declaration//GEN-END:variables

    public javax.swing.JTextField getTextFieldSlika() {
        return TextFieldSlika;
    }

    public void setTextFieldSlika(javax.swing.JTextField TextFieldSlika) {
        this.TextFieldSlika = TextFieldSlika;
    }

    public String getIdTextField() {
        return idTextField.getText();
    }

    public void setId(String id) {
        this.idTextField.setText(id);
    }

    public javax.swing.JTable getjTable1() {
        return jTable1;
    }

    public void setjTable1(javax.swing.JTable jTable1) {
        this.jTable1 = jTable1;
    }

    public String getOpis() {
        return jTextAreaOpis.getText();
    }

    public void setOpis(String text) {
        jTextAreaOpis.setText(text);
    }

    public String getNazivZadatka() {
        return nazivZadatkaTextField.getText();
    }

    public void setNazivZadatka(String text) {
        this.nazivZadatkaTextField.setText(text);
    }

    public String getRok() {
        return rokTextField.getText();

    }

    public void setRok(javax.swing.JTextField rokTextField) {
        this.rokTextField = rokTextField;
    }

    public String getStatus() {
        return statusTextField.getText();
    }

    public void setStatus(String status) {
        statusTextField.setText(status);
    }

    public Zadatak getTrenutniZadatak() {
        return trenutniZadatak;
    }

    public void setTrenutniZadatak(Zadatak trenutniZadatak) {
        this.trenutniZadatak = trenutniZadatak;
    }

    public void resetujSvaPolja() {
        idTextField.setText("");
        nazivZadatkaTextField.setText("");
        rokTextField.setText("");
        statusTextField.setText("");
        jTextAreaOpis.setText("");
        TextFieldSlika.setText("");
        imagePreview.setIcon(null);

    }

}
