/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package imageprocessing.view;

import imageprocessing.filter.EdgeDetection;
import imageprocessing.filter.GrayscaleFilter;
import imageprocessing.filter.HistogramEqualizationFilter;
import imageprocessing.filter.ImageFilter;
import imageprocessing.filter.ImageFilterChain;
import imageprocessing.filter.MedianFilter;
import imageprocessing.filter.OtsuBinarizeFilter;
import java.awt.Component;
import java.awt.PopupMenu;
import java.awt.image.CropImageFilter;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 *
 * @author aleksandar
 */
public class FilteriZaPreprocesiranjePanel extends javax.swing.JPanel {

    //models fo jList
    DefaultListModel allFiltersLM;
    DefaultListModel selectedFiltersLM;
    List<JPanel> parametersPanels;

    /**
     * Creates new form ImagePreprocessingPanel
     */
    public FilteriZaPreprocesiranjePanel() {
        parametersPanels = new ArrayList<>();
        initComponents();
        setLists();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        filtersList = new javax.swing.JList();
        rightButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        selectedFiltersList = new javax.swing.JList();
        leftButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setViewportView(filtersList);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 90, 232, 180));

        rightButton.setText(">>");
        rightButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rightButtonActionPerformed(evt);
            }
        });
        add(rightButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, -1, -1));

        selectedFiltersList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                selectedFiltersListMouseClicked(evt);
            }
        });
        selectedFiltersList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                selectedFiltersListValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(selectedFiltersList);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 90, 232, 181));

        leftButton.setText("<<");
        leftButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leftButtonActionPerformed(evt);
            }
        });
        add(leftButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 170, -1, -1));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel1.setText("Izaberi filtere");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel2.setText("Filteri:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 62, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel3.setText("Izabrani filteri:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Move filter from all filters to selected filters
     *
     * @param evt
     */
    private void rightButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rightButtonActionPerformed
        List<ImageFilter> selected = filtersList.getSelectedValuesList();
        for (ImageFilter imageFilter : selected) {
            //Ne moze vise od 3 filtera!
            if (selectedFiltersLM.size() > 3) {
                break;
            }
            selectedFiltersLM.addElement(imageFilter);
        }

    }//GEN-LAST:event_rightButtonActionPerformed
    /**
     * Move filter from selected filters to all filters
     *
     * @param evt
     */
    private void leftButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leftButtonActionPerformed
        List<ImageFilter> selected = selectedFiltersList.getSelectedValuesList();
        for (ImageFilter imageFilter : selected) {
//            allFiltersLM.addElement(imageFilter);
            selectedFiltersLM.removeElement(imageFilter);
        }
    }//GEN-LAST:event_leftButtonActionPerformed

    private void selectedFiltersListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selectedFiltersListMouseClicked

    }//GEN-LAST:event_selectedFiltersListMouseClicked

    private void selectedFiltersListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_selectedFiltersListValueChanged
    }//GEN-LAST:event_selectedFiltersListValueChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList filtersList;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton leftButton;
    private javax.swing.JButton rightButton;
    private javax.swing.JList selectedFiltersList;
    // End of variables declaration//GEN-END:variables

    /**
     * Set models and add all filters to allFiltersLM
     */
    private void setLists() {

        selectedFiltersLM = new DefaultListModel();
        selectedFiltersList.setModel(selectedFiltersLM);

        allFiltersLM = new DefaultListModel();
        addAllFilters();
        filtersList.setModel(allFiltersLM);

    }

    private void addAllFilters() {
        allFiltersLM.addElement(new GrayscaleFilter());
        allFiltersLM.addElement(new HistogramEqualizationFilter());
        allFiltersLM.addElement(new MedianFilter());
        allFiltersLM.addElement(new OtsuBinarizeFilter());
        allFiltersLM.addElement(new EdgeDetection());

    }

    /**
     * Creates filter chain
     *
     * @return ImageFilterChain
     */
    public ImageFilterChain getImageFilterChain() {
        ImageFilterChain chain = new ImageFilterChain();
        for (Object imageFilter : selectedFiltersLM.toArray()) {
            chain.addFilter((ImageFilter) imageFilter);
        }
        return chain;
    }

}
