/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view;

import view.panel.opstaekranskaforma.OpstaEkranskaForma;

/**
 *
 * @author aleksandar
 */
public class FMenadzer extends javax.swing.JFrame implements OpstaEkranskaForma{

    /**
     * Creates new form FMenadzer form.
     */
    public FMenadzer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtabbedPane = new javax.swing.JTabbedPane();
        UnosRadnikaPanel = new javax.swing.JPanel();
        unosRadnikaPanel1 = new view.panel.radnik.UnosRadnikaPanel();
        UnosZadatkaPanel = new javax.swing.JPanel();
        unosZadatkaPanel1 = new view.panel.zadatak.UnosZadatkaPanel();
        PretragaPanel = new javax.swing.JPanel();
        pretragaZadatakaPanel1 = new view.panel.zadatak.PretragaZadatakaPanel();
        IzmenaZadatakPanel = new javax.swing.JPanel();
        izmenaBrisanjeBiciklistaPanel2 = new view.panel.zadatak.IzmenaBrisanjeZadatakaPanel();
        EvidentiranjePanel = new javax.swing.JPanel();
        evidentiranjePanel1 = new view.panel.zadatak.EvidentiranjePanel();
        ZaduzenjePanel = new javax.swing.JPanel();
        dodeljivanjeZadatkaPanel2 = new view.panel.zadatak.DodeljivanjeZadatkaPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menadzer form");
        setPreferredSize(new java.awt.Dimension(710, 552));

        jtabbedPane.setPreferredSize(new java.awt.Dimension(710, 525));

        javax.swing.GroupLayout UnosRadnikaPanelLayout = new javax.swing.GroupLayout(UnosRadnikaPanel);
        UnosRadnikaPanel.setLayout(UnosRadnikaPanelLayout);
        UnosRadnikaPanelLayout.setHorizontalGroup(
            UnosRadnikaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UnosRadnikaPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(unosRadnikaPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(420, Short.MAX_VALUE))
        );
        UnosRadnikaPanelLayout.setVerticalGroup(
            UnosRadnikaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UnosRadnikaPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(unosRadnikaPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(199, Short.MAX_VALUE))
        );

        jtabbedPane.addTab("Unos radnika", UnosRadnikaPanel);

        UnosZadatkaPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        UnosZadatkaPanel.add(unosZadatkaPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 600, 460));

        jtabbedPane.addTab("Unos zadatka", UnosZadatkaPanel);

        javax.swing.GroupLayout PretragaPanelLayout = new javax.swing.GroupLayout(PretragaPanel);
        PretragaPanel.setLayout(PretragaPanelLayout);
        PretragaPanelLayout.setHorizontalGroup(
            PretragaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PretragaPanelLayout.createSequentialGroup()
                .addComponent(pretragaZadatakaPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 103, Short.MAX_VALUE))
        );
        PretragaPanelLayout.setVerticalGroup(
            PretragaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PretragaPanelLayout.createSequentialGroup()
                .addComponent(pretragaZadatakaPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jtabbedPane.addTab("Pretraga zadataka", PretragaPanel);

        javax.swing.GroupLayout IzmenaZadatakPanelLayout = new javax.swing.GroupLayout(IzmenaZadatakPanel);
        IzmenaZadatakPanel.setLayout(IzmenaZadatakPanelLayout);
        IzmenaZadatakPanelLayout.setHorizontalGroup(
            IzmenaZadatakPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IzmenaZadatakPanelLayout.createSequentialGroup()
                .addComponent(izmenaBrisanjeBiciklistaPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 62, Short.MAX_VALUE))
        );
        IzmenaZadatakPanelLayout.setVerticalGroup(
            IzmenaZadatakPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IzmenaZadatakPanelLayout.createSequentialGroup()
                .addComponent(izmenaBrisanjeBiciklistaPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jtabbedPane.addTab("Izmena i brisanje", IzmenaZadatakPanel);

        evidentiranjePanel1.setBorder(null);

        javax.swing.GroupLayout EvidentiranjePanelLayout = new javax.swing.GroupLayout(EvidentiranjePanel);
        EvidentiranjePanel.setLayout(EvidentiranjePanelLayout);
        EvidentiranjePanelLayout.setHorizontalGroup(
            EvidentiranjePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(evidentiranjePanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        EvidentiranjePanelLayout.setVerticalGroup(
            EvidentiranjePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(evidentiranjePanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jtabbedPane.addTab("Evidentiranje", EvidentiranjePanel);

        ZaduzenjePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        ZaduzenjePanel.add(dodeljivanjeZadatkaPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jtabbedPane.addTab("Zaduzenje", ZaduzenjePanel);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jtabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 733, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jtabbedPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 515, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FMenadzer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FMenadzer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FMenadzer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FMenadzer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FMenadzer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel EvidentiranjePanel;
    private javax.swing.JPanel IzmenaZadatakPanel;
    private javax.swing.JPanel PretragaPanel;
    private javax.swing.JPanel UnosRadnikaPanel;
    private javax.swing.JPanel UnosZadatkaPanel;
    private javax.swing.JPanel ZaduzenjePanel;
    private view.panel.zadatak.DodeljivanjeZadatkaPanel dodeljivanjeZadatkaPanel2;
    private view.panel.zadatak.EvidentiranjePanel evidentiranjePanel1;
    private view.panel.zadatak.IzmenaBrisanjeZadatakaPanel izmenaBrisanjeBiciklistaPanel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JTabbedPane jtabbedPane;
    private view.panel.zadatak.PretragaZadatakaPanel pretragaZadatakaPanel1;
    private view.panel.radnik.UnosRadnikaPanel unosRadnikaPanel1;
    private view.panel.zadatak.UnosZadatkaPanel unosZadatkaPanel1;
    // End of variables declaration//GEN-END:variables
}
